CREATE TABLE inventory_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT NOT NULL,
    supplier_id BIGINT,
    name VARCHAR(150) NOT NULL,
    sku VARCHAR(50) NOT NULL,
    unit VARCHAR(20) NOT NULL,
    current_stock DECIMAL(15,3) NOT NULL DEFAULT 0.000,
    minimum_stock DECIMAL(15,3) NOT NULL DEFAULT 0.000,
    maximum_stock DECIMAL(15,3),
    reorder_level DECIMAL(15,3) NOT NULL DEFAULT 0.000,
    unit_cost DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_inventory_items_sku UNIQUE (sku),
    CONSTRAINT fk_inventory_items_category
        FOREIGN KEY (category_id) REFERENCES inventory_categories(id),
    CONSTRAINT fk_inventory_items_supplier
        FOREIGN KEY (supplier_id) REFERENCES suppliers(id),
    CONSTRAINT chk_inventory_items_current_stock CHECK (current_stock >= 0),
    CONSTRAINT chk_inventory_items_minimum_stock CHECK (minimum_stock >= 0),
    CONSTRAINT chk_inventory_items_maximum_stock
        CHECK (maximum_stock IS NULL OR maximum_stock >= 0),
    CONSTRAINT chk_inventory_items_reorder_level CHECK (reorder_level >= 0),
    CONSTRAINT chk_inventory_items_unit_cost CHECK (unit_cost >= 0)
);

CREATE INDEX idx_inventory_items_category_id ON inventory_items(category_id);
CREATE INDEX idx_inventory_items_supplier_id ON inventory_items(supplier_id);
CREATE INDEX idx_inventory_items_name ON inventory_items(name);
CREATE INDEX idx_inventory_items_enabled ON inventory_items(enabled);
