CREATE TABLE stock_movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inventory_item_id BIGINT NOT NULL,
    movement_type VARCHAR(30) NOT NULL,
    quantity DECIMAL(15,3) NOT NULL,
    stock_before DECIMAL(15,3) NOT NULL,
    stock_after DECIMAL(15,3) NOT NULL,
    unit_cost DECIMAL(15,2),
    reference_type VARCHAR(50),
    reference_id BIGINT,
    reason VARCHAR(255),
    created_by BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_stock_movements_inventory_item
        FOREIGN KEY (inventory_item_id) REFERENCES inventory_items(id),
    CONSTRAINT chk_stock_movements_quantity CHECK (quantity > 0),
    CONSTRAINT chk_stock_movements_stock_before CHECK (stock_before >= 0),
    CONSTRAINT chk_stock_movements_stock_after CHECK (stock_after >= 0),
    CONSTRAINT chk_stock_movements_unit_cost
        CHECK (unit_cost IS NULL OR unit_cost >= 0)
);

CREATE INDEX idx_stock_movements_inventory_item_id ON stock_movements(inventory_item_id);
CREATE INDEX idx_stock_movements_movement_type ON stock_movements(movement_type);
CREATE INDEX idx_stock_movements_created_at ON stock_movements(created_at);
CREATE INDEX idx_stock_movements_reference
    ON stock_movements(reference_type, reference_id);
