CREATE TABLE purchase_order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_order_id BIGINT NOT NULL,
    inventory_item_id BIGINT NOT NULL,
    quantity DECIMAL(15,3) NOT NULL,
    unit_cost DECIMAL(15,2) NOT NULL,
    total_cost DECIMAL(15,2) NOT NULL,

    CONSTRAINT fk_purchase_order_items_order
        FOREIGN KEY (purchase_order_id)
        REFERENCES purchase_orders(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_purchase_order_items_inventory
        FOREIGN KEY (inventory_item_id)
        REFERENCES inventory_items(id),
    CONSTRAINT chk_purchase_order_items_quantity CHECK (quantity > 0),
    CONSTRAINT chk_purchase_order_items_unit_cost CHECK (unit_cost >= 0),
    CONSTRAINT chk_purchase_order_items_total_cost CHECK (total_cost >= 0)
);

CREATE INDEX idx_purchase_order_items_order_id
    ON purchase_order_items(purchase_order_id);
CREATE INDEX idx_purchase_order_items_inventory_item_id
    ON purchase_order_items(inventory_item_id);
