CREATE TABLE inventory_item_batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inventory_item_id BIGINT NOT NULL,
    batch_number VARCHAR(100) NOT NULL,
    received_quantity DECIMAL(15,3) NOT NULL,
    remaining_quantity DECIMAL(15,3) NOT NULL,
    unit_cost DECIMAL(15,2) NOT NULL,
    received_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expiry_date DATE,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_inventory_item_batch
        UNIQUE (inventory_item_id, batch_number),
    CONSTRAINT fk_inventory_item_batches_item
        FOREIGN KEY (inventory_item_id) REFERENCES inventory_items(id),
    CONSTRAINT chk_inventory_item_batches_received_quantity
        CHECK (received_quantity > 0),
    CONSTRAINT chk_inventory_item_batches_remaining_quantity
        CHECK (remaining_quantity >= 0),
    CONSTRAINT chk_inventory_item_batches_unit_cost
        CHECK (unit_cost >= 0)
);

CREATE INDEX idx_inventory_item_batches_item_id
    ON inventory_item_batches(inventory_item_id);
CREATE INDEX idx_inventory_item_batches_expiry_date
    ON inventory_item_batches(expiry_date);
CREATE INDEX idx_inventory_item_batches_enabled
    ON inventory_item_batches(enabled);
