CREATE TABLE recipes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    menu_item_id BIGINT NOT NULL,
    name VARCHAR(150) NOT NULL,
    description VARCHAR(255),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_recipes_menu_item UNIQUE (menu_item_id),
    CONSTRAINT fk_recipes_menu_item
        FOREIGN KEY (menu_item_id) REFERENCES menu_items(id)
);

CREATE INDEX idx_recipes_enabled ON recipes(enabled);
