CREATE TABLE recipe_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipe_id BIGINT NOT NULL,
    inventory_item_id BIGINT NOT NULL,
    quantity DECIMAL(15,3) NOT NULL,

    CONSTRAINT fk_recipe_items_recipe
        FOREIGN KEY (recipe_id) REFERENCES recipes(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_recipe_items_inventory
        FOREIGN KEY (inventory_item_id) REFERENCES inventory_items(id),
    CONSTRAINT uk_recipe_items_recipe_inventory
        UNIQUE (recipe_id, inventory_item_id),
    CONSTRAINT chk_recipe_items_quantity CHECK (quantity > 0)
);

CREATE INDEX idx_recipe_items_recipe_id ON recipe_items(recipe_id);
CREATE INDEX idx_recipe_items_inventory_item_id ON recipe_items(inventory_item_id);
